#!/usr/bin/env python
#
import csv

def r1(fname):
  out1 = open("happy-sad-training.csv", "w")
  out2 = open("happy-sad-privtest.csv", "w")
  out3 = open("happy-sad-pubtest.csv", "w")
  with open(fname, 'r') as csvfile:
    rdr = csv.reader(csvfile)
    i = j = 0
    for row in rdr:
      if i > 0:
        # At this point, row[] is an array of 3 items
        emotion_type = int(row[0])
        if emotion_type == 3 or emotion_type == 4:
          t2 = emotion_type - 3
          # Tagged happy or sad
          # print (', '.join(row))
          lstr = row[1].split(" ")
          outpt = (",".join(lstr)) + "," + str(t2) + "\n"
          if row[2] == 'Training':
            out1.write(outpt)
          elif row[2] == 'PrivateTest':
            out2.write(outpt)
          else:
            out3.write(outpt)
      i = i + 1
  out1.close()
  out2.close()
  out3.close()

r1('fer2013.csv')
