#!/usr/bin/env python
#
import csv

emo_map = (-1,  # angry
           -1, # disgust
           -1, # fear
           0,  # happy
           1,  # sad
           -1, # surprise
           -1) # neutral

def r1(fname):
  out1 = open("three-emotions-unified.csv", "w")
  with open(fname, 'r') as csvfile:
    rdr = csv.reader(csvfile)
    i = j = 0
    for row in rdr:
      if i > 0:
        # At this point, row[] is an array of 3 items
        emotion_type = int(row[0])
        if emo_map[emotion_type] >= 0:
          t2 = emo_map[emotion_type]
          lstr = row[1].split(" ")
          outpt = (",".join(lstr)) + "," + str(t2) + "\n"
          out1.write(outpt)
      i = i + 1
  out1.close()

r1('fer2013.csv')
